Carolina González Salinas A01662120
# Obtención de estadísticas descriptivas  
  
  Cargamos los datos:

In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv("avocado.csv")

Cantidad y tipo de datos:

In [14]:
tot_datos = df.shape
print("Total de datos por columna:", tot_datos[0])
print("Total de datos en la DataFrame:", tot_datos[0]*tot_datos[1])
print("Tipos de variable de cada columna:")
print(df.dtypes)

Total de datos por columna: 18249
Total de datos en la DataFrame: 255486
Tipos de variable de cada columna:
Unnamed: 0        int64
Date             object
AveragePrice    float64
Total Volume    float64
4046            float64
4225            float64
4770            float64
Total Bags      float64
Small Bags      float64
Large Bags      float64
XLarge Bags     float64
type             object
year              int64
region           object
dtype: object


Análisis de variables:  
Unnamed: índice  
Date: fecha  
AveragePrice: Precio promedio de los aguacates  
Total Volume: Volumen total de los aguacates  
4046: indeterminado  
4225: indeterminado  
4770: indeterminado  
Total Bags: Valor total de las bolsas  
Small Bags: Valor de las bolsas pequeñas  
Large Bags: Valor de las bolsas grandes  
XLarge Bags: Valor de las bolsas enormes  
type: tipo de aguacate  
year: Año de la venta  
region: Lugar de la venta  


In [18]:
def rango(variable):
    print("Rango", variable, df[variable].min(), "-", df[variable].max())

rango('Unnamed: 0')
rango('Date')
rango('AveragePrice')
rango('Total Volume')
rango('4046')
rango('4225')
rango('4770')
rango('Total Bags')
rango('Small Bags')
rango('Large Bags')
rango('XLarge Bags')
rango('type')
rango('year')
rango('region')


Rango Unnamed: 0 0 - 52
Rango Date 2015-01-04 - 2018-03-25
Rango AveragePrice 0.44 - 3.25
Rango Total Volume 84.56 - 62505646.52
Rango 4046 0.0 - 22743616.17
Rango 4225 0.0 - 20470572.61
Rango 4770 0.0 - 2546439.11
Rango Total Bags 0.0 - 19373134.37
Rango Small Bags 0.0 - 13384586.8
Rango Large Bags 0.0 - 5719096.61
Rango XLarge Bags 0.0 - 551693.65
Rango type conventional - organic
Rango year 2015 - 2018
Rango region Albany - WestTexNewMexico


Conclusiones basadas en la media, mediana y desviación estándar:

In [20]:
def medidas(variable):
    media = np.mean(df[variable])
    mediana = np.median(df[variable])
    desv_est = np.std(df[variable])
    print("Medidas para la columna:", variable)
    print("Media:", media)
    print("Mediana:", mediana)
    print("Desviación Estándar:", desv_est)

for columna in df:
    try:
        medidas(columna)
    except:
        print("La columna", columna, "no es numérica")
    finally:
        print("")

Medidas para la columna: Unnamed: 0
Media: 24.232231903117977
Mediana: 24.0
Desviación Estándar: 15.480620586492071

La columna Date no es numérica

Medidas para la columna: AveragePrice
Media: 1.405978409775878
Mediana: 1.37
Desviación Estándar: 0.4026655225054672

Medidas para la columna: Total Volume
Media: 850644.0130089321
Mediana: 107376.76
Desviación Estándar: 3453450.731237377

Medidas para la columna: 4046
Media: 293008.4245306592
Mediana: 8645.3
Desviación Estándar: 1264954.422153708

Medidas para la columna: 4225
Media: 295154.56835607433
Mediana: 29061.02
Desviación Estándar: 1204087.4092752968

Medidas para la columna: 4770
Media: 22839.73599265713
Mediana: 184.99
Desviación Estándar: 107461.12401264436

Medidas para la columna: Total Bags
Media: 239639.20205983886
Mediana: 39743.83
Desviación Estándar: 986215.3770258671

Medidas para la columna: Small Bags
Media: 182194.68669570936
Mediana: 26362.82
Desviación Estándar: 746158.0703144815

Medidas para la columna: Large Ba

Conclusiones de los datos:
La columna Unnamed: 0 no nos da ninguna información relevante porque es un índice
Las columnas Date, type y region no son numéricas, entonces no podemos sacarles media, mediana o desviación estándar.
La columna AveragePrice tiene una media y mediana muy cercanas, además de una desviación estándar baja, lo cuál indica que todos los datos de esta columna tienden a ser bastante similares. Esto implica que los precios casi rondan un precio preestablecido, lo cuál es normal en cualquier economía: Tenemos muchos precios muy similares y unos pocos muy bajos o muy altos (esto lo notamos por el rango dado más arriba) por tener muy baja o muy alta calidad.
Las columnas Total Volume, 4046, 4225, 4770, Total Bags, Small Bags, Large Bags y XLarge Bags cuentan con medianas muy por debajo de la media y desviaciones estándar grandes. Esto nos habla de que la variabilidad de estos datos es muy grande, aunque tienden a tener muchos datos por debajo de la media y pocos datos muy por encima de la media.
La columna year tiene una media, mediana cercanas y una desviación estándar baja, lo cuál indica que todos los datos de esta columna tienden a ser bastante similares. Tomando en cuenta que el rango de esta columna es del 2015 al 2018, tiene sentido que no haya mucha variabilidad en los datos.